// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE8fRIEn7zyPUtWqMGp9grXChm70NqyCo',
    appId: '1:856939611735:web:c3cd88d2439be5cf7b0512',
    messagingSenderId: '856939611735',
    projectId: 'uitconnect-f20a8',
    authDomain: 'uitconnect-f20a8.firebaseapp.com',
    storageBucket: 'uitconnect-f20a8.firebasestorage.app',
    measurementId: 'G-ZDWC6PPRC9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi4CnqbJIqrSBFVgR_Em4up-cFIa_51OU',
    appId: '1:856939611735:android:a3ec4bcc951e383b7b0512',
    messagingSenderId: '856939611735',
    projectId: 'uitconnect-f20a8',
    storageBucket: 'uitconnect-f20a8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuHUTy7FLbhkNpdCaxwv7AszMeQRVtPeM',
    appId: '1:856939611735:ios:3c845335954e62e77b0512',
    messagingSenderId: '856939611735',
    projectId: 'uitconnect-f20a8',
    storageBucket: 'uitconnect-f20a8.firebasestorage.app',
    iosBundleId: 'com.example.uithelp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuHUTy7FLbhkNpdCaxwv7AszMeQRVtPeM',
    appId: '1:856939611735:ios:3c845335954e62e77b0512',
    messagingSenderId: '856939611735',
    projectId: 'uitconnect-f20a8',
    storageBucket: 'uitconnect-f20a8.firebasestorage.app',
    iosBundleId: 'com.example.uithelp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAE8fRIEn7zyPUtWqMGp9grXChm70NqyCo',
    appId: '1:856939611735:web:d74c6bc81002d3f27b0512',
    messagingSenderId: '856939611735',
    projectId: 'uitconnect-f20a8',
    authDomain: 'uitconnect-f20a8.firebaseapp.com',
    storageBucket: 'uitconnect-f20a8.firebasestorage.app',
    measurementId: 'G-YQM4KEEMXL',
  );
}
